### ISSUE TITLE
Error assembleDebug

### ISSUE THREAD

**Issue by CapitainOats** [rickspm/Business-Inventory-App#1]
I have problem to assembleDebug. From messages gradle build package name of multiple classes clashes with the class of same name.

But there are clearly another errors going on.

![snimek obrazovky 2017-12-03 v 10 22 28](https://user-images.githubusercontent.com/17655140/33523974-e8f67f3a-d813-11e7-8855-458ee3435bd4.png)

**Comment by rickspm** [comment]
Just fixed and it's working for me now. Can you try again and let me know if everything is okay?

**Comment by CapitainOats** [comment]
Perfect, issue is solved. 👍
